/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddaxResult: typeof import('./src/components/ods/AddaxResult.vue')['default']
    AddDataSource: typeof import('./src/components/datasource/AddDataSource.vue')['default']
    BatchAdd: typeof import('./src/components/ods/BatchAdd.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    CmdList: typeof import('./src/components/ods/CmdList.vue')['default']
    DialogComp: typeof import('./src/components/ods/DialogComp.vue')['default']
    DSTableDetail: typeof import('./src/components/dataservice/DSTableDetail.vue')['default']
    DSTableFields: typeof import('./src/components/dataservice/DSTableFields.vue')['default']
    FieldsCompare: typeof import('./src/components/ods/FieldsCompare.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    L5TEtlBar: typeof import('./src/components/dashboard/L5TEtlBar.vue')['default']
    LineChart: typeof import('./src/components/dashboard/LineChart.vue')['default']
    LogFiles: typeof import('./src/components/ods/LogFiles.vue')['default']
    LogModal: typeof import('./src/components/ods/LogModal.vue')['default']
    MainTable: typeof import('./src/components/ods/MainTable.vue')['default']
    MainTableInfo: typeof import('./src/components/dataservice/MainTableInfo.vue')['default']
    NavbarThemeSwitcher: typeof import('./src/components/NavbarThemeSwitcher.vue')['default']
    PieChart: typeof import('./src/components/dashboard/PieChart.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneList: typeof import('./src/components/sp/SceneList.vue')['default']
    ShowLogs: typeof import('./src/components/sp/ShowLogs.vue')['default']
    SpCmdList: typeof import('./src/components/sp/SpCmdList.vue')['default']
    SpComp: typeof import('./src/components/sp/SpComp.vue')['default']
    SpDetail: typeof import('./src/components/sp/SpDetail.vue')['default']
    SpLineage: typeof import('./src/components/sp/SpLineage.vue')['default']
    SpRequiresList: typeof import('./src/components/sp/SpRequiresList.vue')['default']
    TableUsed: typeof import('./src/components/ods/TableUsed.vue')['default']
  }
}
