/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddaxResult: typeof import('./src/components/table/AddaxResult.vue')['default']
    AddSource: typeof import('./src/components/source/AddSource.vue')['default']
    AppBreadcrumb: typeof import('./src/components/AppBreadcrumb.vue')['default']
    AppRegister: typeof import('./src/components/AppRegister.vue')['default']
    BatchAdd: typeof import('./src/components/table/BatchAdd.vue')['default']
    BatchUpdate: typeof import('./src/components/table/BatchUpdate.vue')['default']
    CmdList: typeof import('./src/components/table/CmdList.vue')['default']
    DialogComp: typeof import('./src/components/table/DialogComp.vue')['default']
    FieldsCompare: typeof import('./src/components/table/FieldsCompare.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    L5TEtlBar: typeof import('./src/components/dashboard/L5TEtlBar.vue')['default']
    LineChart: typeof import('./src/components/dashboard/LineChart.vue')['default']
    LogFiles: typeof import('./src/components/table/LogFiles.vue')['default']
    LogModal: typeof import('./src/components/table/LogModal.vue')['default']
    MainTable: typeof import('./src/components/table/MainTable.vue')['default']
    NavbarThemeSwitcher: typeof import('./src/components/NavbarThemeSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableUsed: typeof import('./src/components/table/TableUsed.vue')['default']
  }
}
