/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/closed-check': RouteRecordInfo<'/closed-check', '/closed-check', Record<never, never>, Record<never, never>>,
    '/demo': RouteRecordInfo<'/demo', '/demo', Record<never, never>, Record<never, never>>,
    '/etl-monitor': RouteRecordInfo<'/etl-monitor', '/etl-monitor', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/maintable/data-service': RouteRecordInfo<'/maintable/data-service', '/maintable/data-service', Record<never, never>, Record<never, never>>,
    '/maintable/data-sources': RouteRecordInfo<'/maintable/data-sources', '/maintable/data-sources', Record<never, never>, Record<never, never>>,
    '/maintable/ods-etl': RouteRecordInfo<'/maintable/ods-etl', '/maintable/ods-etl', Record<never, never>, Record<never, never>>,
    '/maintable/params': RouteRecordInfo<'/maintable/params', '/maintable/params', Record<never, never>, Record<never, never>>,
    '/maintable/plan-task': RouteRecordInfo<'/maintable/plan-task', '/maintable/plan-task', Record<never, never>, Record<never, never>>,
    '/maintable/sp': RouteRecordInfo<'/maintable/sp', '/maintable/sp', Record<never, never>, Record<never, never>>,
    '/plan-task': RouteRecordInfo<'/plan-task', '/plan-task', Record<never, never>, Record<never, never>>,
    '/realtime': RouteRecordInfo<'/realtime', '/realtime', Record<never, never>, Record<never, never>>,
    '/risk-monitor': RouteRecordInfo<'/risk-monitor', '/risk-monitor', Record<never, never>, Record<never, never>>,
    '/sp-monitor': RouteRecordInfo<'/sp-monitor', '/sp-monitor', Record<never, never>, Record<never, never>>,
    '/system-info': RouteRecordInfo<'/system-info', '/system-info', Record<never, never>, Record<never, never>>,
    '/task-group': RouteRecordInfo<'/task-group', '/task-group', Record<never, never>, Record<never, never>>,
  }
}
