/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/closecheck': RouteRecordInfo<'/closecheck', '/closecheck', Record<never, never>, Record<never, never>>,
    '/demo': RouteRecordInfo<'/demo', '/demo', Record<never, never>, Record<never, never>>,
    '/etl': RouteRecordInfo<'/etl', '/etl', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/maintable/': RouteRecordInfo<'/maintable/', '/maintable', Record<never, never>, Record<never, never>>,
    '/maintable/mbdatasource': RouteRecordInfo<'/maintable/mbdatasource', '/maintable/mbdatasource', Record<never, never>, Record<never, never>>,
    '/maintable/mbds': RouteRecordInfo<'/maintable/mbds', '/maintable/mbds', Record<never, never>, Record<never, never>>,
    '/maintable/mbods': RouteRecordInfo<'/maintable/mbods', '/maintable/mbods', Record<never, never>, Record<never, never>>,
    '/maintable/mbparam': RouteRecordInfo<'/maintable/mbparam', '/maintable/mbparam', Record<never, never>, Record<never, never>>,
    '/maintable/mbsp': RouteRecordInfo<'/maintable/mbsp', '/maintable/mbsp', Record<never, never>, Record<never, never>>,
    '/maintable/plantask': RouteRecordInfo<'/maintable/plantask', '/maintable/plantask', Record<never, never>, Record<never, never>>,
    '/plantask': RouteRecordInfo<'/plantask', '/plantask', Record<never, never>, Record<never, never>>,
    '/realtime': RouteRecordInfo<'/realtime', '/realtime', Record<never, never>, Record<never, never>>,
    '/risk': RouteRecordInfo<'/risk', '/risk', Record<never, never>, Record<never, never>>,
    '/spmonitor': RouteRecordInfo<'/spmonitor', '/spmonitor', Record<never, never>, Record<never, never>>,
    '/systeminfo': RouteRecordInfo<'/systeminfo', '/systeminfo', Record<never, never>, Record<never, never>>,
    '/taskgroup': RouteRecordInfo<'/taskgroup', '/taskgroup', Record<never, never>, Record<never, never>>,
  }
}
