/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddaxJob: typeof import('./../components/table/AddaxJob.vue')['default']
    AddaxResult: typeof import('./../components/table/AddaxResult.vue')['default']
    AddSource: typeof import('./../components/source/AddSource.vue')['default']
    AppBreadcrumb: typeof import('./../components/AppBreadcrumb.vue')['default']
    AppRegister: typeof import('./../components/AppRegister.vue')['default']
    BatchAdd: typeof import('./../components/table/BatchAdd.vue')['default']
    BatchUpdate: typeof import('./../components/table/BatchUpdate.vue')['default']
    DialogComp: typeof import('./../components/table/DialogComp.vue')['default']
    FieldsCompare: typeof import('./../components/table/FieldsCompare.vue')['default']
    L5TEtlBar: typeof import('./../components/dashboard/L5TEtlBar.vue')['default']
    LineChart: typeof import('./../components/dashboard/LineChart.vue')['default']
    LogFiles: typeof import('./../components/table/LogFiles.vue')['default']
    LogModal: typeof import('./../components/table/LogModal.vue')['default']
    NavbarThemeSwitcher: typeof import('./../components/NavbarThemeSwitcher.vue')['default']
    Notifier: typeof import('./../components/Notifier.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableDetail: typeof import('./../components/table/TableDetail.vue')['default']
    TaskEtlProgress: typeof import('./../components/task/TaskEtlProgress.vue')['default']
    TaskList: typeof import('./../components/task/TaskList.vue')['default']
  }
}
